group: bionic

language: node_js

node_js:
  - 14
  - 16
# - 18

before_install:
- npm i -g npm@8
- npm --version

script:
- npm run build
- npm run test-travis || travis_terminate 1
- npm run lint
- npm run check-packages

