dist: focal

# Remove this if using external Travis
group: beta

language: node_js

node_js:
# - 14
# - 16
# - 18

# remove the "echo" command from the "before_install" section below.
before_install:
- echo -e "machine github.ibm.com\n  login $GITHUB_OAUTH_TOKEN" > ~/.netrc
- npm i -g npm@8
- npm --version

script:
- npm run build
- npm run test-travis || travis_terminate 1
- npm run lint
- npm run check-packages

